version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=/models/DeepSeek-R1-Distill-Qwen-7B
    volumes:
      - ./models:/models

  ide:
    build: ./ide
    ports:
      - "8080:8080"
    volumes:
      - .:/workspace
    depends_on:
      - api